"""
CuraGo — PostgreSQL / Relational Database Layer
=====================================================

This module is aligned with the current UUID / SERIAL PostgreSQL schema and
provides enterprise-grade Data Access Objects (DAO) for the backend API.

Schema assumptions handled here:
  - PostgreSQL generates UUID / BIGSERIAL primary keys.
  - Soft deletion is enforced: `deleted_at IS NULL` must be appended to core queries.
  - Health measurements enforce strict BP logic: `systolic_bp > diastolic_bp`.
  - HNSW indexing and `vector_cosine_ops` are used for AI embedding similarity search.

Important implementation details:
  - All SQL uses parameterized inputs to prevent SQL injection.
  - Read queries use autocommit connections for performance.
  - Write operations (execute_*) use explicit `conn.autocommit = False`, bundled inside 
    `try...except...conn.rollback()` blocks to ensure ACID compliance.
  - Unknown lookups return `None` or `(False, message)` rather than raising application errors.
"""

import hashlib
import secrets
from datetime import datetime, timezone
from typing import Any, Optional
from uuid import UUID
from contextlib import contextmanager

import psycopg2
import psycopg2.extras
from psycopg2.pool import ThreadedConnectionPool
from pgvector.psycopg2 import register_vector
from psycopg2.extras import RealDictCursor

from skeleton.config import DB_CONFIG

# ── Database Connection Pool Setup ───────────────────────────────────────────

# 利用 config.py 的字典動態組裝連線字串
PG_DSN = f"dbname={DB_CONFIG['dbname']} user={DB_CONFIG['user']} password={DB_CONFIG['password']} host={DB_CONFIG['host']} port={DB_CONFIG['port']}"

# 初始化連線池 (設定最少 1 個，最多 20 個連線)
db_pool = ThreadedConnectionPool(1, 20, PG_DSN)

@contextmanager
def get_db_connection(autocommit: bool = True):
    """
    從 ThreadedConnectionPool 取得連線，並確保使用完畢後自動歸還。
    預設為 autocommit=True (適合純讀取)。寫入操作請傳入 autocommit=False。
    """
    conn = db_pool.getconn()
    conn.autocommit = autocommit
    try:
        register_vector(conn)
        yield conn
    finally:
        db_pool.putconn(conn)

# ── connection / id / security helpers ───────────────────────────────────────

def _is_uuid(value: Any) -> bool:
    try:
        UUID(str(value))
        return True
    except Exception:
        return False

def _hash_password(value: str | None) -> str | None:
    """Hash a password using Argon2id when available, or fallback to PBKDF2."""
    if value is None:
        return None

    try:
        from argon2 import PasswordHasher  # type: ignore
        return PasswordHasher().hash(str(value))
    except ImportError:
        iterations = 100_000
        salt = secrets.token_hex(16)
        hashed = hashlib.pbkdf2_hmac(
            "sha256",
            str(value).encode("utf-8"),
            salt.encode("utf-8"),
            iterations,
        ).hex()
        return f"$argon2id$pbkdf2_fallback$v=19$i={iterations}${salt}${hashed}"

def _verify_password(value: str, stored_hash: str | None) -> bool:
    """Verify password_hash generated by _hash_password()."""
    if not value or not stored_hash:
        return False

    if stored_hash.startswith("$argon2id$pbkdf2_fallback$"):
        try:
            parts = stored_hash.split("$")
            iterations = int(parts[4].split("=", 1)[1])
            salt = parts[5]
            expected_hash = parts[6]
            actual_hash = hashlib.pbkdf2_hmac(
                "sha256",
                str(value).encode("utf-8"),
                salt.encode("utf-8"),
                iterations,
            ).hex()
            return secrets.compare_digest(actual_hash, expected_hash)
        except Exception:
            return False

    if stored_hash.startswith("$argon2id$"):
        try:
            from argon2 import PasswordHasher  # type: ignore
            from argon2.exceptions import VerifyMismatchError  # type: ignore
            try:
                return PasswordHasher().verify(stored_hash, str(value))
            except VerifyMismatchError:
                return False
        except Exception:
            return False

    return False

def _resolve_user_pk(cur, user_ref: Any) -> Optional[str]:
    """Resolve users.id from UUID or email, enforcing soft-delete check."""
    if user_ref is None:
        return None

    ref = str(user_ref)
    if _is_uuid(ref):
        cur.execute("SELECT id FROM users WHERE id = %s::uuid AND deleted_at IS NULL;", (ref,))
    elif "@" in ref:
        cur.execute("SELECT id FROM users WHERE email = %s AND deleted_at IS NULL;", (ref,))
    else:
        return None

    row = cur.fetchone()
    return str(row["id"]) if row else None

def _resolve_elder_pk(cur, elder_ref: Any) -> Optional[str]:
    """Resolve elders.id from UUID, enforcing soft-delete check."""
    if not elder_ref or not _is_uuid(elder_ref):
        return None

    cur.execute("SELECT id FROM elders WHERE id = %s::uuid AND deleted_at IS NULL;", (str(elder_ref),))
    row = cur.fetchone()
    return str(row["id"]) if row else None

# ── AUTHENTICATION QUERIES ───────────────────────────────────────────────────

def register_user(email: str, phone: str, full_name: str, password: str, role: str) -> tuple[bool, str]:
    """Register a new user. Returns (True, user_id) or (False, error_message)."""
    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                # 1. 檢查信箱是否已存在
                cur.execute("SELECT 1 FROM users WHERE email = %s;", (email,))
                if cur.fetchone():
                    conn.rollback()
                    return False, "Email is already registered."

                # 2. 驗證角色合法性
                if role not in ('family', 'caregiver', 'admin'):
                    conn.rollback()
                    return False, "Invalid role specified."

                password_hash = _hash_password(password)
                if password_hash is None:
                    conn.rollback()
                    return False, "Password cannot be empty."

                # 3. 執行寫入
                cur.execute(
                    """
                    INSERT INTO users (email, phone, password_hash, full_name, role)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id;
                    """,
                    (email, phone, password_hash, full_name, role)
                )
                
                new_user = cur.fetchone()
                conn.commit()
                return True, str(new_user["id"])

        except Exception as e:
            conn.rollback()
            return False, str(e)

def login_user(email: str, password: str) -> Optional[dict]:
    """Verify password hash and return a user dict on success, else None."""
    sql_select = """
        SELECT
            id AS user_id,
            email,
            phone,
            full_name,
            role,
            password_hash
        FROM users
        WHERE email = %s
          AND deleted_at IS NULL;
    """
    sql_update = "UPDATE users SET last_login_at = NOW() WHERE id = %s"

    with get_db_connection(autocommit=False) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            # 1. 查詢使用者
            cur.execute(sql_select, (email,))
            row = cur.fetchone()

            # 2. 驗證失敗則 rollback 並提早結束
            if not row or not _verify_password(password, row["password_hash"]):
                conn.rollback()
                return None

            # 3. 驗證成功，使用同一個 cursor 直接更新最後登入時間
            try:
                cur.execute(sql_update, (row["user_id"],))
                conn.commit()
            except Exception:
                conn.rollback()

            return {
                "user_id": str(row["user_id"]),
                "email": row["email"],
                "phone": row["phone"],
                "full_name": row["full_name"],
                "role": row["role"]
            }

# ── DASHBOARD & GROUPS ───────────────────────────────────────────────────────

def query_authorized_elders(user_ref: str) -> list[dict]:
    """Return all elders the user has permission to view."""
    sql = """
        SELECT 
            e.id AS elder_id,
            e.name AS elder_name,
            e.birth_date,
            e.emergency_phone,
            cg.id AS group_id,
            cg.group_name,
            gm.role_in_group
        FROM group_members gm
        JOIN care_groups cg ON gm.group_id = cg.id
        JOIN elders e ON cg.elder_id = e.id
        WHERE gm.user_id = %s 
          AND e.deleted_at IS NULL;
    """
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            user_pk = _resolve_user_pk(cur, user_ref)
            if not user_pk:
                return []
                
            cur.execute(sql, (user_pk,))
            return [dict(row) for row in cur.fetchall()]

# ── EMERGENCY PUSH SYSTEM ────────────────────────────────────────────────────

def query_emergency_push_tokens(elder_id: str, exclude_user_id: Optional[str] = None) -> list[dict]:
    """Retrieve FCM tokens for all active devices belonging to the elder's care group."""
    sql = """
        SELECT DISTINCT ud.fcm_token, ud.device_type, u.full_name, u.id AS user_id
        FROM elders e
        JOIN care_groups cg ON e.id = cg.elder_id
        JOIN group_members gm ON cg.id = gm.group_id
        JOIN users u ON gm.user_id = u.id
        JOIN user_devices ud ON u.id = ud.user_id
        WHERE e.id = %s 
          AND u.deleted_at IS NULL 
          AND e.deleted_at IS NULL
    """
    params = [elder_id]
    if exclude_user_id:
        sql += " AND u.id != %s"
        params.append(exclude_user_id)

    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            elder_pk = _resolve_elder_pk(cur, elder_id)
            if not elder_pk:
                return []
                
            cur.execute(sql, tuple(params))
            return [dict(row) for row in cur.fetchall()]

# ── TASK OPERATIONS ──────────────────────────────────────────────────────────

def query_daily_pending_tasks(elder_id: str) -> list[dict]:
    """Retrieve today's pending tasks for a specific elder."""
    sql = """
        SELECT 
            t.id AS task_id,
            t.task_type,
            t.scheduled_time,
            u.full_name AS assigned_caregiver_name
        FROM tasks t
        LEFT JOIN users u ON t.assigned_to = u.id
        WHERE t.elder_id = %s
          AND t.status = 'pending'
          AND DATE(t.scheduled_time AT TIME ZONE 'UTC') = CURRENT_DATE
          AND t.deleted_at IS NULL
        ORDER BY t.scheduled_time ASC;
    """
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            elder_pk = _resolve_elder_pk(cur, elder_id)
            if not elder_pk:
                return []
                
            cur.execute(sql, (elder_pk,))
            return [dict(row) for row in cur.fetchall()]

def execute_complete_task(task_id: str) -> tuple[bool, str | dict]:
    """Atomically mark a task as completed."""
    if not _is_uuid(task_id):
        return False, "Invalid task ID format."

    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                cur.execute(
                    """
                    UPDATE tasks 
                    SET status = 'completed', 
                        completed_at = NOW() 
                    WHERE id = %s 
                      AND status = 'pending'
                      AND deleted_at IS NULL
                    RETURNING id, elder_id, task_type, completed_at;
                    """,
                    (str(task_id),)
                )
                updated_task = cur.fetchone()
                
                if not updated_task:
                    conn.rollback()
                    return False, "Task not found, already completed, or deleted."

                conn.commit()
                return True, dict(updated_task)

        except Exception as e:
            conn.rollback()
            return False, str(e)

# ── HEALTH & AI MEASUREMENTS ─────────────────────────────────────────────────

def execute_record_health_measurement(
    elder_id: str,
    measured_at: str,
    data_source: str = 'manual',
    heart_rate: Optional[int] = None,
    systolic_bp: Optional[int] = None,
    diastolic_bp: Optional[int] = None,
    blood_sugar: Optional[float] = None,
    meal_context: Optional[str] = None,
    ai_evaluation: Optional[str] = None,
    ai_reasoning: Optional[str] = None,
    ai_suggestion: Optional[str] = None,
) -> tuple[bool, str | dict]:
    """
    Insert a health measurement. Relies on DB constraints (e.g., systolic > diastolic)
    to enforce medical data integrity.
    """
    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                elder_pk = _resolve_elder_pk(cur, elder_id)
                if not elder_pk:
                    conn.rollback()
                    return False, "Elder not found or deleted."

                cur.execute(
                    """
                    INSERT INTO health_measurements (
                        elder_id, heart_rate, systolic_bp, diastolic_bp, blood_sugar, 
                        meal_context, data_source, ai_evaluation, ai_reasoning, 
                        ai_suggestion, measured_at
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                    ) RETURNING id, measured_at, created_at;
                    """,
                    (
                        elder_pk, heart_rate, systolic_bp, diastolic_bp, blood_sugar,
                        meal_context, data_source, ai_evaluation, ai_reasoning,
                        ai_suggestion, measured_at
                    )
                )
                record = cur.fetchone()
                conn.commit()
                return True, dict(record)

        except psycopg2.errors.CheckViolation as e:
            conn.rollback()
            return False, f"Data validation failed (Check Constraint Violation): {e}"
        except Exception as e:
            conn.rollback()
            return False, str(e)

# ── AI VECTOR & EVENT SEARCH ─────────────────────────────────────────────────

def query_similar_historical_events(elder_id: str, embedding_vector: list[float], limit: int = 3) -> list[dict]:
    """Find the most semantically similar historical events using pgvector Cosine Distance."""
    if len(embedding_vector) != 768:
        raise ValueError("Embedding vector must be exactly 768 dimensions.")

    sql = """
        SELECT 
            id AS event_id,
            original_text,
            severity,
            status,
            created_at,
            (embedding <=> %s::vector) AS cosine_distance
        FROM events
        WHERE elder_id = %s
          AND deleted_at IS NULL
          AND embedding IS NOT NULL
        ORDER BY embedding <=> %s::vector
        LIMIT %s;
    """
    
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            elder_pk = _resolve_elder_pk(cur, elder_id)
            if not elder_pk:
                return []
                
            cur.execute(sql, (embedding_vector, elder_pk, embedding_vector, limit))
            return [dict(row) for row in cur.fetchall()]

# ── AUDIT LOGS ───────────────────────────────────────────────────────────────

def query_audit_trail(table_name: str, record_id: str) -> list[dict]:
    """Retrieve the modification history of a specific record for legal/audit purposes."""
    sql = """
        SELECT 
            action,
            old_data,
            new_data,
            changed_at
        FROM audit_logs
        WHERE table_name = %s 
          AND record_id = %s
        ORDER BY changed_at DESC;
    """
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (table_name, str(record_id)))
            return [dict(row) for row in cur.fetchall()]

# ── EVENT OPERATIONS (AI & 家屬端) ──────────────────────────────────────────

def execute_create_event(
    elder_id: str,
    reporter_id: str,
    source_language: str,
    original_text: str,
    event_type: str,
    severity: str,
    normalized_text: Optional[str] = None,
    translations: Optional[dict] = None,
    embedding_vector: Optional[list[float]] = None
) -> tuple[bool, str | dict]:
    """
    接收 AI 層辨識完的結果，建立一筆新的異常事件。
    包含多國語言翻譯 (JSONB) 與語意向量 (Vector)。
    """
    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                elder_pk = _resolve_elder_pk(cur, elder_id)
                reporter_pk = _resolve_user_pk(cur, reporter_id)
                
                if not elder_pk or not reporter_pk:
                    conn.rollback()
                    return False, "Elder or Reporter not found."

                cur.execute(
                    """
                    INSERT INTO events (
                        elder_id, reporter_id, source_language, original_text, 
                        normalized_text, translations, embedding, 
                        event_type, severity, status
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s::vector, %s, %s, 'pending'
                    ) RETURNING id, created_at;
                    """,
                    (
                        elder_pk, reporter_pk, source_language, original_text,
                        normalized_text, psycopg2.extras.Json(translations or {}), 
                        embedding_vector,
                        event_type, severity
                    )
                )
                new_event = cur.fetchone()
                conn.commit()
                return True, dict(new_event)

        except Exception as e:
            conn.rollback()
            return False, str(e)

# ==========================================
# Health Metrics: 健康數據讀取 (寫入已在上方 execute_record_health_measurement)
# ==========================================
def query_recent_health_measurements(elder_id: str, limit: int = 10) -> list[dict]:
    """取得長者最近的健康數據"""
    sql = "SELECT id, heart_rate, systolic_bp, diastolic_bp, blood_sugar, meal_context, data_source, measured_at FROM health_measurements WHERE elder_id = %s ORDER BY measured_at DESC LIMIT %s;"
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            elder_pk = _resolve_elder_pk(cur, elder_id)
            if not elder_pk: 
                return []
            cur.execute(sql, (elder_pk, limit))
            return [dict(row) for row in cur.fetchall()]

# ==========================================
# Users & Elders: 帳號與長者基本資料
# ==========================================
def get_user_profile(user_id: str) -> Optional[dict]:
    """取得照護人員/家屬的資料"""
    sql = "SELECT id, full_name as name, email, role FROM users WHERE id = %s AND deleted_at IS NULL;"
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            if not _is_uuid(user_id): return None
            cur.execute(sql, (user_id,))
            row = cur.fetchone()
            return dict(row) if row else None

def get_elder_profile(elder_id: str) -> Optional[dict]:
    """取得長者的基本資料"""
    sql = "SELECT id, name, birth_date, emergency_phone FROM elders WHERE id = %s AND deleted_at IS NULL;"
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            if not _is_uuid(elder_id): return None
            cur.execute(sql, (elder_id,))
            row = cur.fetchone()
            return dict(row) if row else None

# ==========================================
# Notifications: 通知系統
# ==========================================
def get_user_notifications(user_id: str, limit: int = 20) -> list[dict]:
    """取得使用者的未讀/歷史通知"""
    sql = "SELECT id, title, content, is_read, created_at FROM notifications WHERE user_id = %s ORDER BY created_at DESC LIMIT %s;"
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            if not _is_uuid(user_id): return []
            cur.execute(sql, (user_id, limit))
            return [dict(row) for row in cur.fetchall()]

def mark_notification_read(notification_id: str) -> bool:
    """標記通知為已讀"""
    sql = "UPDATE notifications SET is_read = TRUE WHERE id = %s RETURNING id;"
    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor() as cur:
                if not _is_uuid(notification_id): return False
                cur.execute(sql, (notification_id,))
                success = cur.fetchone() is not None
                conn.commit()
                return success
        except Exception:
            conn.rollback()
            return False

# ==========================================
# Chat & Devices: 聊天室與裝置綁定
# ==========================================
def get_group_messages(group_id: str, limit: int = 50) -> list[dict]:
    """取得照護群組的歷史對話"""
    sql = "SELECT id, sender_id, message_type, content, created_at FROM chat_messages WHERE group_id = %s ORDER BY created_at DESC LIMIT %s;"
    with get_db_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            if not _is_uuid(group_id): return []
            cur.execute(sql, (group_id, limit))
            return [dict(row) for row in cur.fetchall()]

def register_user_device(user_id: str, device_token: str, platform: str) -> bool:
    """綁定使用者的推播裝置 (FCM Token 等)"""
    sql = """
        INSERT INTO user_devices (user_id, fcm_token, device_type) 
        VALUES (%s, %s, %s)
        ON CONFLICT (fcm_token) DO UPDATE SET updated_at = NOW();
    """
    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor() as cur:
                cur.execute(sql, (user_id, device_token, platform))
                conn.commit()
                return True
        except Exception:
            conn.rollback()
            return False

def insert_chat_message(group_id: str, sender_id: str, message_type: str, content: str) -> tuple[bool, str | dict]:
    """將新訊息寫入資料庫"""
    sql = """
        INSERT INTO chat_messages (group_id, sender_id, message_type, content)
        VALUES (%s, %s, %s, %s)
        RETURNING id, created_at;
    """
    with get_db_connection(autocommit=False) as conn:
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                if not _is_uuid(group_id) or not _is_uuid(sender_id):
                    return False, "Invalid ID format"
                
                cur.execute(sql, (group_id, sender_id, message_type, content))
                new_msg = cur.fetchone()
                conn.commit()
                return True, dict(new_msg)
        except Exception as e:
            conn.rollback()
            return False, str(e)